### ISSUE TITLE
Compatibility list

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/wmr#128]
I've been trying out `wmr` in some existing client projects and I'll use this issue as a list to keep track of changes I had to make. Mostly to be aware how we could ease migration to switch to wmr from another build tool.

- [x] Class components typically use class fields #126 
- [x] Importing image files returns the file path as the default export #133 
- [x] `@urql/core` import fails. See #129 and #139 (PR)
- [x] React projects often have a loader for `.svg` files, that returns a `ReactComponent` export
- [x] Node-resolution like `/foo -> /foo/index.js`, imports without extension basically #138 
- [x] Error overlay

**Comment by joaopaulobdac** [comment]
What are the differences between WMR and preact-cli? Is it that WMR replaces webpack?

**Comment by developit** [comment]
That's one of the biggest differences, yeah - WMR uses Rollup, and only in production (during development it uses Rollup's plugin API but not Rollup itself). Other than that the design is fairly different - Preact CLI tends to be more prescriptive about things (the `src/routes` folder, `async!` prefixes, pre-rendering config file, CSS Modules by default in some directories, etc). WMR is more generic, with the details of things like lazy loading and routing left up to you (though we provide the `preact-iso` library as a helper).
